import { lazy } from 'react';
import { widgetRegistry } from '@hugescreen/core';

export function registerBuiltinWidgets(): void {
  widgetRegistry.registerAll([
    // ─── 统计卡 ───
    {
      type: 'stat-card',
      name: '统计卡',
      description: '关键指标数值及趋势',
      icon: 'TrendingUp',
      category: 'stat',
      defaultSize: { colSpan: 2, rowSpan: 2 },
      minSize: { colSpan: 1, rowSpan: 1 },
      maxSize: { colSpan: 4, rowSpan: 3 },
      component: lazy(() => import('./stat-card/StatCard').then(m => ({ default: m.StatCard }))),
      configSchema: {
        type: 'object',
        properties: {
          title: { type: 'string', title: '标题' },
          value: { type: 'number', title: '数值' },
          format: { type: 'string', title: '格式', enum: ['number', 'currency', 'percent'] },
        },
      },
      defaultConfig: { title: '指标', value: 0, format: 'number', showTrend: false, trendMode: 'auto', trendLabel: '', showIcon: false },
    },

    // ─── HUD 环形仪表（暂时隐藏）───
    // {
    //   type: 'hud-gauge',
    //   name: 'HUD 仪表',
    //   description: '7 层同心 HUD 环形进度指示器',
    //   icon: 'Gauge',
    //   category: 'stat',
    //   defaultSize: { colSpan: 2, rowSpan: 2 },
    //   minSize: { colSpan: 1, rowSpan: 1 },
    //   maxSize: { colSpan: 3, rowSpan: 3 },
    //   component: lazy(() => import('./stat-card/HudGauge').then(m => ({ default: m.HudGauge }))),
    //   configSchema: { type: 'object', properties: { percent: { type: 'number', title: '百分比' }, label: { type: 'string', title: '副标题' } } },
    //   defaultConfig: { percent: 98, label: 'CHONGDIANJINXIN' },
    // },

    // ─── 折线图 ───
    {
      type: 'line-chart',
      name: '折线图',
      description: '数据趋势变化',
      icon: 'LineChart',
      category: 'chart',
      defaultSize: { colSpan: 4, rowSpan: 6 },
      minSize: { colSpan: 2, rowSpan: 2 },
      maxSize: { colSpan: 8, rowSpan: 6 },
      component: lazy(() => import('./charts/LineChartWidget').then(m => ({ default: m.LineChartWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          smooth: { type: 'boolean', title: '平滑曲线' },
          showArea: { type: 'boolean', title: '显示面积' },
          xLabels: { type: 'array', title: 'X轴标签' },
          lineSeries: { type: 'array', title: '数据系列' },
        },
      },
      defaultConfig: {
        smooth: true,
        showArea: true,
        xLabels: ['周一', '周二', '周三', '周四', '周五', '周六', '周日'],
        lineSeries: [
          { name: '系列1', data: [120, 200, 150, 80, 70, 110, 130] },
        ],
      },
    },

    // ─── 柱状图（含条形图模式）───
    {
      type: 'bar-chart',
      name: '柱状图',
      description: '竖向柱状或横向条形',
      icon: 'BarChart3',
      category: 'chart',
      defaultSize: { colSpan: 2, rowSpan: 2 },
      minSize: { colSpan: 2, rowSpan: 1 },
      maxSize: { colSpan: 4, rowSpan: 3 },
      component: lazy(() => import('./charts/BarChartWidget').then(m => ({ default: m.BarChartWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          direction: { type: 'string', title: '呈现方式', enum: ['vertical', 'horizontal'] },
          showLabel: { type: 'boolean', title: '显示数值' },
          categories: { type: 'array', title: '数据类别' },
        },
      },
      defaultConfig: {
        direction: 'vertical',
        showLabel: false,
        showTick: true,
        colorBySign: false,
        labelFontSize: '10px', labelFontWeight: '600', labelColor: '#FF8C42', barWidth: '50%',
        categories: [
          { name: '类别A', value: 182 },
          { name: '类别B', value: 234 },
          { name: '类别C', value: 165 },
          { name: '类别D', value: 298 },
          { name: '类别E', value: 210 },
        ],
      },
    },

    // ─── 柱线组合图（双 Y 轴）───
    {
      type: 'bar-line-chart',
      name: '柱线组合图',
      description: '柱状 + 折线双 Y 轴',
      icon: 'BarChart3',
      category: 'chart',
      defaultSize: { colSpan: 4, rowSpan: 4 },
      minSize: { colSpan: 2, rowSpan: 2 },
      maxSize: { colSpan: 8, rowSpan: 6 },
      component: lazy(() => import('./charts/BarLineChartWidget').then(m => ({ default: m.BarLineChartWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          smooth: { type: 'boolean', title: '平滑曲线' },
          showArea: { type: 'boolean', title: '面积填充' },
          barWidth: { type: 'string', title: '柱宽' },
          showLabel: { type: 'boolean', title: '显示数值' },
          xLabels: { type: 'array', title: 'X轴标签' },
          mixedSeries: { type: 'array', title: '混合系列' },
        },
      },
      defaultConfig: {
        smooth: true,
        showArea: false,
        barWidth: '50%',
        showLabel: false,
        showTick: true,
        colorBySign: false,
        xLabels: ['2020', '2021', '2022', '2023', '2024', '2025'],
        mixedSeries: [
          { name: '带宽', unit: 'T', type: 'bar', data: [0.6, 1.1, 1.8, 2.4, 3.2, 3.9] },
          { name: '机柜数', unit: '个', type: 'line', data: [120, 230, 410, 620, 850, 1080] },
        ],
      },
    },

    // ─── 饼图 ───
    {
      type: 'pie-chart',
      name: '饼图',
      description: '占比分布环形图',
      icon: 'PieChart',
      category: 'chart',
      defaultSize: { colSpan: 2, rowSpan: 2 },
      minSize: { colSpan: 2, rowSpan: 2 },
      maxSize: { colSpan: 3, rowSpan: 3 },
      component: lazy(() => import('./charts/PieChartWidget').then(m => ({ default: m.PieChartWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          donut: { type: 'boolean', title: '环形' },
          showLegend: { type: 'boolean', title: '图例' },
          showColorLegend: { type: 'boolean', title: '颜色图例' },
          titleText: { type: 'string', title: '图名' },
          titlePosition: { type: 'string', title: '图名位置', enum: ['none', 'topLeft', 'bottom'] },
          roseType: { type: 'string', title: '玫瑰图', enum: ['none', 'radius', 'area'] },
          categories: { type: 'array', title: '数据类别' },
        },
      },
      defaultConfig: {
        donut: true,
        showLegend: false,
        showColorLegend: true,
        titleText: '',
        titlePosition: 'none',
        roseType: 'none',
        categories: [
          { name: '类别A', value: 335 },
          { name: '类别B', value: 310 },
          { name: '类别C', value: 234 },
          { name: '类别D', value: 135 },
          { name: '类别E', value: 548 },
        ],
      },
    },

    // ─── 漏斗图 ───
    {
      type: 'funnel-chart',
      name: '漏斗图',
      description: '梯形转化占比分布',
      icon: 'Filter',
      category: 'chart',
      defaultSize: { colSpan: 3, rowSpan: 4 },
      minSize: { colSpan: 2, rowSpan: 2 },
      maxSize: { colSpan: 6, rowSpan: 8 },
      component: lazy(() => import('./charts/FunnelWidget').then(m => ({ default: m.FunnelWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          sortMode: { type: 'string', title: '排序', enum: ['desc', 'asc', 'none'] },
          gap: { type: 'number', title: '层间距' },
          funnelAlign: { type: 'string', title: '对齐', enum: ['left', 'center', 'right'] },
          labelPosition: { type: 'string', title: '标签位置', enum: ['inside', 'outer'] },
          showPercent: { type: 'boolean', title: '标签百分比' },
          showLegend: { type: 'boolean', title: '图例' },
          categories: { type: 'array', title: '数据类别' },
        },
      },
      defaultConfig: {
        sortMode: 'desc',
        gap: 2,
        funnelAlign: 'center',
        labelPosition: 'inside',
        showPercent: false,
        showLegend: true,
        categories: [
          { name: '展现', value: 100 },
          { name: '点击', value: 80 },
          { name: '访问', value: 60 },
          { name: '咨询', value: 40 },
          { name: '订单', value: 20 },
        ],
      },
    },

    // ─── 图片 ───
    {
      type: 'image-widget',
      name: '图片',
      description: '图片展示',
      icon: 'Image',
      category: 'decorator',
      defaultSize: { colSpan: 2, rowSpan: 2 },
      minSize: { colSpan: 1, rowSpan: 1 },
      maxSize: { colSpan: 6, rowSpan: 6 },
      component: lazy(() => import('./decorators/ImageWidget').then(m => ({ default: m.ImageWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          src: { type: 'string', title: '图片数据' },
          opacity: { type: 'number', title: '透明度' },
          fit: { type: 'string', title: '填充方式', enum: ['contain', 'cover', 'fill'] },
        },
      },
      defaultConfig: {
        src: '',
        opacity: 1,
        fit: 'contain',
      },
    },

    // ─── 文本 ───
    {
      type: 'text-widget',
      name: '文本',
      description: '自定义文字显示',
      icon: 'Type',
      category: 'decorator',
      defaultSize: { colSpan: 2, rowSpan: 1 },
      minSize: { colSpan: 1, rowSpan: 1 },
      maxSize: { colSpan: 6, rowSpan: 3 },
      component: lazy(() => import('./decorators/TextWidget').then(m => ({ default: m.TextWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          text: { type: 'string', title: '文字内容' },
          fontSize: { type: 'string', title: '字号' },
          fontWeight: { type: 'string', title: '字重' },
          fontStyle: { type: 'string', title: '斜体' },
          color: { type: 'string', title: '颜色' },
          textAlign: { type: 'string', title: '对齐' },
        },
      },
      defaultConfig: {
        text: '输入文字',
        fontSize: '16px',
        fontWeight: '400',
        fontStyle: 'normal',
        color: '#E8E8EC',
        textAlign: 'center',
      },
    },

    // ─── 赛博地图 ───
    {
      type: 'cyber-map',
      name: '赛博地图',
      description: '3D 赛博风格行政区划地图，支持地图钉配置',
      icon: 'Map',
      category: '3d',
      defaultSize: { colSpan: 6, rowSpan: 6 },
      minSize: { colSpan: 3, rowSpan: 3 },
      maxSize: { colSpan: 12, rowSpan: 12 },
      component: lazy(() => import('./geo/CyberMapWidget').then(m => ({ default: m.CyberMapWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          thickness: { type: 'number', title: '厚度' },
          showGrid: { type: 'boolean', title: '显示网格' },
        },
      },
      defaultConfig: {
        thickness: 3,
        showGrid: true,
        pinTypes: [],
        pinInstances: [],
      },
    },

    {
      type: 'video-widget',
      name: '视频',
      description: '本地视频或直播流播放',
      icon: 'Video',
      category: 'media',
      defaultSize: { colSpan: 3, rowSpan: 3 },
      minSize: { colSpan: 2, rowSpan: 2 },
      maxSize: { colSpan: 6, rowSpan: 6 },
      component: lazy(() => import('./decorators/VideoWidget').then(m => ({ default: m.VideoWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          videos: { type: 'array', title: '视频列表' },
          fit: { type: 'string', title: '填充方式', enum: ['contain', 'cover', 'fill'] },
          muted: { type: 'boolean', title: '静音' },
          autoplay: { type: 'boolean', title: '自动播放' },
          loop: { type: 'boolean', title: '循环播放' },
          controls: { type: 'boolean', title: '播放控件' },
          preload: { type: 'string', title: '预加载', enum: ['metadata', 'auto', 'none'] },
        },
      },
      defaultConfig: {
        videos: [],
        fit: 'contain',
        muted: true,
        autoplay: true,
        loop: true,
        controls: false,
        preload: 'metadata',
      },
    },

    {
      type: 'box-plot',
      name: '箱线图',
      description: '数据分布盒须图，展示最小值/Q1/中位数/Q3/最大值',
      icon: 'BarChart4',
      category: 'chart',
      defaultSize: { colSpan: 4, rowSpan: 3 },
      minSize: { colSpan: 3, rowSpan: 2 },
      maxSize: { colSpan: 8, rowSpan: 5 },
      component: lazy(() => import('./charts/BoxPlotWidget').then(m => ({ default: m.BoxPlotWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          boxColor: { type: 'string', title: '盒子颜色' },
          boxWidth: { type: 'number', title: '盒子宽度' },
          categories: { type: 'array', title: '数据' },
        },
      },
      defaultConfig: {
        boxColor: '#00D4FF',
        boxWidth: 20,
        showTick: true,
        categories: [
          { name: 'A组', min: 10, q1: 30, median: 45, q3: 60, max: 85 },
          { name: 'B组', min: 15, q1: 35, median: 50, q3: 65, max: 90 },
          { name: 'C组', min: 20, q1: 40, median: 55, q3: 70, max: 95 },
          { name: 'D组', min: 12, q1: 32, median: 48, q3: 62, max: 88 },
          { name: 'E组', min: 8,  q1: 28, median: 42, q3: 58, max: 80 },
        ],
      },
    },

    {
      type: 'treemap-chart',
      name: '矩形树图',
      description: '面积层级矩形分布',
      icon: 'Grid3x3',
      category: 'chart',
      defaultSize: { colSpan: 4, rowSpan: 4 },
      minSize: { colSpan: 2, rowSpan: 2 },
      maxSize: { colSpan: 8, rowSpan: 8 },
      component: lazy(() => import('./charts/TreemapWidget').then(m => ({ default: m.TreemapWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          breadcrumb: { type: 'boolean', title: '面包屑' },
          drillDown: { type: 'boolean', title: '点击下钻' },
          treemaps: { type: 'array', title: '树数据' },
        },
      },
      defaultConfig: {
        breadcrumb: true,
        drillDown: true,
        treemaps: [
          {
            name: '总销售额',
            children: [
              { name: '华东', children: [{ name: '上海', value: 320 }, { name: '杭州', value: 180 }, { name: '南京', value: 150 }] },
              { name: '华南', children: [{ name: '广州', value: 260 }, { name: '深圳', value: 240 }] },
              { name: '华北', children: [{ name: '北京', value: 280 }, { name: '天津', value: 120 }] },
              { name: '西南', children: [{ name: '成都', value: 190 }, { name: '重庆', value: 170 }] },
            ],
          },
        ],
      },
    },

    {
      type: 'sunburst-chart',
      name: '旭日图',
      description: '层级环形占比分布',
      icon: 'Orbit',
      category: 'chart',
      defaultSize: { colSpan: 4, rowSpan: 4 },
      minSize: { colSpan: 2, rowSpan: 2 },
      maxSize: { colSpan: 8, rowSpan: 8 },
      component: lazy(() => import('./charts/SunburstWidget').then(m => ({ default: m.SunburstWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          drillDown: { type: 'boolean', title: '点击下钻' },
          clockwise: { type: 'boolean', title: '顺时针' },
          sortMode: { type: 'string', title: '排序', enum: ['none', 'desc', 'asc'] },
          focusMode: { type: 'string', title: '高亮模式', enum: ['ancestor', 'descendant', 'self', 'none'] },
          showLabel: { type: 'boolean', title: '显示标签' },
          sunbursts: { type: 'array', title: '环形数据' },
        },
      },
      defaultConfig: {
        drillDown: true,
        clockwise: true,
        sortMode: 'none',
        focusMode: 'ancestor',
        showLabel: true,
        sunbursts: [
          {
            name: '总销售额',
            children: [
              { name: '华东', children: [{ name: '上海', value: 320 }, { name: '杭州', value: 180 }, { name: '南京', value: 150 }] },
              { name: '华南', children: [{ name: '广州', value: 260 }, { name: '深圳', value: 240 }] },
              { name: '华北', children: [{ name: '北京', value: 280 }, { name: '天津', value: 120 }] },
              { name: '西南', children: [{ name: '成都', value: 190 }, { name: '重庆', value: 170 }] },
            ],
          },
        ],
      },
    },

    {
      type: 'multiple-x-axis-chart',
      name: '多 X 轴走势图',
      description: '上下双轴十字交叉走势',
      icon: 'MoveHorizontal',
      category: 'chart',
      defaultSize: { colSpan: 4, rowSpan: 4 },
      minSize: { colSpan: 2, rowSpan: 2 },
      maxSize: { colSpan: 8, rowSpan: 8 },
      component: lazy(() => import('./charts/MultipleXAxisWidget').then(m => ({ default: m.MultipleXAxisWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          bottomColor: { type: 'string', title: '底部线颜色' },
          topColor: { type: 'string', title: '顶部线颜色' },
          smooth: { type: 'boolean', title: '平滑曲线' },
          showLegend: { type: 'boolean', title: '显示图例' },
          labelRotate: { type: 'number', title: '轴标签旋转' },
          showAxisLabel: { type: 'boolean', title: '显示轴标签' },
          bottom: { type: 'object', title: '底部数据' },
          top: { type: 'object', title: '顶部数据' },
        },
      },
      defaultConfig: {
        bottomColor: '#00D4FF',
        topColor: '#FF8C42',
        smooth: true,
        showLegend: true,
        labelRotate: 20,
        showAxisLabel: true,
        bottom: {
          labels: ['周一', '周二', '周三', '周四', '周五', '周六', '周日'],
          values: [12, 23, 34, 45, 56, 67, 78],
        },
        top: {
          labels: ['甲', '乙', '丙', '丁', '戊', '己', '庚'],
          values: [11.2, 6.3, 4.5, 5.7, 12.4, 15.7, 3.5],
        },
      },
    },

    // ─── 表格类 ───
    {
      type: 'marquee-table',
      name: '环形滚动表格',
      description: '表头固定，行数据无缝循环滚动',
      icon: 'Table2',
      category: 'table',
      defaultSize: { colSpan: 3, rowSpan: 3 },
      minSize: { colSpan: 2, rowSpan: 2 },
      maxSize: { colSpan: 8, rowSpan: 8 },
      component: lazy(() => import('./table/MarqueeTableWidget').then(m => ({ default: m.MarqueeTableWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          speed: { type: 'number', title: '滚动速度' },
          direction: { type: 'string', title: '方向', enum: ['up', 'down'] },
          pauseOnHover: { type: 'boolean', title: '悬停暂停' },
          headerColor: { type: 'string', title: '表头颜色' },
          headers: { type: 'array', title: '表头' },
          rows: { type: 'array', title: '行数据' },
        },
      },
      defaultConfig: {
        speed: 28,
        direction: 'up',
        pauseOnHover: true,
        headerColor: '#00D4FF',
        headers: ['排名', '地区', '销售额', '同比'],
        rows: [
          ['1', '华东', 320, '+12.4%'],
          ['2', '华南', 260, '+8.2%'],
          ['3', '华北', 240, '+15.7%'],
          ['4', '西南', 190, '-3.5%'],
          ['5', '华中', 170, '+5.1%'],
        ],
      },
    },

    {
      type: 'tree-chart',
      name: '树形图',
      description: '层级关系树，四向可切换',
      icon: 'GitBranch',
      category: 'chart',
      defaultSize: { colSpan: 4, rowSpan: 4 },
      minSize: { colSpan: 2, rowSpan: 2 },
      maxSize: { colSpan: 8, rowSpan: 8 },
      component: lazy(() => import('./charts/TreeChartWidget').then(m => ({ default: m.TreeChartWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          orient: { type: 'string', title: '朝向', enum: ['LR', 'TB', 'RL', 'BT'] },
          nodeColor: { type: 'string', title: '节点颜色' },
          expandCollapse: { type: 'boolean', title: '展开折叠' },
          initialDepth: { type: 'number', title: '初始深度' },
          trees: { type: 'array', title: '树数据' },
        },
      },
      defaultConfig: {
        orient: 'LR',
        nodeColor: '#00D4FF',
        expandCollapse: true,
        initialDepth: 2,
        trees: [
          {
            name: '总部',
            children: [
              { name: '华东区', children: [{ name: '上海' }, { name: '杭州' }, { name: '南京' }] },
              { name: '华南区', children: [{ name: '广州' }, { name: '深圳' }] },
              { name: '华北区', children: [{ name: '北京' }, { name: '天津' }] },
            ],
          },
        ],
      },
    },

    {
      type: 'relation-chart',
      name: '关系图',
      description: '节点连线关系网络',
      icon: 'Network',
      category: 'chart',
      defaultSize: { colSpan: 4, rowSpan: 4 },
      minSize: { colSpan: 2, rowSpan: 2 },
      maxSize: { colSpan: 8, rowSpan: 8 },
      component: lazy(() => import('./charts/RelationChartWidget').then(m => ({ default: m.RelationChartWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          nodeColor: { type: 'string', title: '节点颜色' },
          lineColor: { type: 'string', title: '连线颜色' },
          hideOverlap: { type: 'boolean', title: '隐藏重叠标签' },
          nodes: { type: 'array', title: '节点' },
          links: { type: 'array', title: '连线' },
        },
      },
      defaultConfig: {
        nodeColor: '#00D4FF',
        hideOverlap: true,
      },
    },

    {
      type: 'sankey-chart',
      name: '桑基图',
      description: '节点流量流向分布',
      icon: 'Waypoints',
      category: 'chart',
      defaultSize: { colSpan: 4, rowSpan: 4 },
      minSize: { colSpan: 2, rowSpan: 2 },
      maxSize: { colSpan: 8, rowSpan: 8 },
      component: lazy(() => import('./charts/SankeyWidget').then(m => ({ default: m.SankeyWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          orient: { type: 'string', title: '布局方向', enum: ['horizontal', 'vertical'] },
          focusMode: { type: 'string', title: '高亮模式', enum: ['adjacency', 'none'] },
          nodeWidth: { type: 'number', title: '节点宽度' },
          nodeGap: { type: 'number', title: '节点间距' },
          lineOpacity: { type: 'number', title: '连线透明度' },
          nodes: { type: 'array', title: '节点' },
          links: { type: 'array', title: '连线' },
        },
      },
      defaultConfig: {
        orient: 'horizontal',
        focusMode: 'adjacency',
        nodeWidth: 14,
        nodeGap: 12,
        lineOpacity: 0.35,
        nodes: [
          { name: '总流量', value: 30 },
          { name: '渠道A', value: 15 },
          { name: '渠道B', value: 15 },
          { name: '上海', value: 8 },
          { name: '杭州', value: 7 },
          { name: '广州', value: 9 },
          { name: '成都', value: 6 },
        ],
        links: [
          { source: '总流量', target: '渠道A', value: 15 },
          { source: '总流量', target: '渠道B', value: 15 },
          { source: '渠道A', target: '上海', value: 8 },
          { source: '渠道A', target: '杭州', value: 7 },
          { source: '渠道B', target: '广州', value: 9 },
          { source: '渠道B', target: '成都', value: 6 },
        ],
      },
    },

    {
      type: 'heatmap',
      name: '热力图',
      description: '二维密度分布，支持大数据量',
      icon: 'Grid3x3',
      category: 'chart',
      defaultSize: { colSpan: 4, rowSpan: 3 },
      minSize: { colSpan: 2, rowSpan: 2 },
      maxSize: { colSpan: 8, rowSpan: 5 },
      component: lazy(() => import('./charts/HeatmapWidget').then(m => ({ default: m.HeatmapWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          points: { type: 'array', title: '数据' },
        },
      },
      defaultConfig: {
        showTick: true,
      },
    },

    {
      type: 'radar-chart',
      name: '雷达图',
      description: '多维指标对比',
      icon: 'Radar',
      category: 'chart',
      defaultSize: { colSpan: 3, rowSpan: 3 },
      minSize: { colSpan: 2, rowSpan: 2 },
      maxSize: { colSpan: 6, rowSpan: 6 },
      component: lazy(() => import('./charts/RadarChartWidget').then(m => ({ default: m.RadarChartWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          lineColor: { type: 'string', title: '线颜色' },
          areaColor: { type: 'string', title: '面积颜色' },
          indicators: { type: 'array', title: '指标' },
          series: { type: 'array', title: '数据' },
        },
      },
      defaultConfig: {
        lineColor: '#00D4FF',
        areaColor: '#00D4FF',
      },
    },

    {
      type: 'intraday-chart',
      name: '断轴走势图',
      description: '时间序列走势，自动跳过休市间隔',
      icon: 'ChartLine',
      category: 'chart',
      defaultSize: { colSpan: 4, rowSpan: 3 },
      minSize: { colSpan: 2, rowSpan: 2 },
      maxSize: { colSpan: 8, rowSpan: 5 },
      component: lazy(() => import('./charts/IntradayChartWidget').then(m => ({ default: m.IntradayChartWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          lineColor: { type: 'string', title: '线颜色' },
          points: { type: 'array', title: '数据' },
        },
      },
      defaultConfig: {
        lineColor: '#00D4FF',
        showTick: true,
      },
    },

    {
      type: 'scatter-plot',
      name: '散点图',
      description: 'X/Y 双值轴数据分布',
      icon: 'ChartScatter',
      category: 'chart',
      defaultSize: { colSpan: 4, rowSpan: 3 },
      minSize: { colSpan: 2, rowSpan: 2 },
      maxSize: { colSpan: 8, rowSpan: 5 },
      component: lazy(() => import('./charts/ScatterPlotWidget').then(m => ({ default: m.ScatterPlotWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          pointColor: { type: 'string', title: '点颜色' },
          symbolSize: { type: 'number', title: '点大小' },
          points: { type: 'array', title: '数据' },
        },
      },
      defaultConfig: {
        pointColor: '#00D4FF',
        symbolSize: 8,
        showTick: true,
      },
    },

    {
      type: 'step-line',
      name: '阶梯线图',
      description: '阶梯状态变化折线',
      icon: 'ChartLine',
      category: 'chart',
      defaultSize: { colSpan: 4, rowSpan: 3 },
      minSize: { colSpan: 2, rowSpan: 2 },
      maxSize: { colSpan: 8, rowSpan: 5 },
      component: lazy(() => import('./charts/StepLineWidget').then(m => ({ default: m.StepLineWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          step: { type: 'string', title: '阶梯拐点', enum: ['start','middle','end'] },
          lineColor: { type: 'string', title: '线颜色' },
          points: { type: 'array', title: '数据' },
        },
      },
      defaultConfig: {
        step: 'middle',
        lineColor: '#00D4FF',
        showTick: true,
      },
    },

    {
      type: 'dynamic-time',
      name: '动态时间轴',
      description: '实时滚动曲线，定时追加数据',
      icon: 'ChartArea',
      category: 'chart',
      defaultSize: { colSpan: 4, rowSpan: 3 },
      minSize: { colSpan: 2, rowSpan: 2 },
      maxSize: { colSpan: 8, rowSpan: 5 },
      component: lazy(() => import('./charts/DynamicTimeWidget').then(m => ({ default: m.DynamicTimeWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          dynamic: { type: 'boolean', title: '动态追加' },
          interval: { type: 'number', title: '更新间隔(ms)' },
          windowSize: { type: 'number', title: '滑窗大小' },
          lineColor: { type: 'string', title: '线颜色' },
          points: { type: 'array', title: '初始数据' },
        },
      },
      defaultConfig: {
        dynamic: true,
        interval: 1000,
        windowSize: 60,
        lineColor: '#00D4FF',
        showTick: true,
      },
    },

    {
      type: 'large-area-chart',
      name: '大规模面积图',
      description: '时间序列面积图，支持大数据量',
      icon: 'ChartArea',
      category: 'chart',
      defaultSize: { colSpan: 4, rowSpan: 3 },
      minSize: { colSpan: 2, rowSpan: 2 },
      maxSize: { colSpan: 8, rowSpan: 5 },
      component: lazy(() => import('./charts/LargeAreaChartWidget').then(m => ({ default: m.LargeAreaChartWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          lineColor: { type: 'string', title: '线颜色' },
          areaColor: { type: 'string', title: '面积颜色' },
          sampling: { type: 'string', title: '降采样', enum: ['lttb','average','max','min','sum','none'] },
          points: { type: 'array', title: '数据' },
        },
      },
      defaultConfig: {
        lineColor: '#00D4FF',
        areaColor: '#00D4FF',
        sampling: 'lttb',
        showTick: true,
      },
    },

    {
      type: 'confidence-band',
      name: '置信区间图',
      description: '主线 + 上下界区间填充',
      icon: 'LineChart',
      category: 'chart',
      defaultSize: { colSpan: 4, rowSpan: 3 },
      minSize: { colSpan: 2, rowSpan: 2 },
      maxSize: { colSpan: 8, rowSpan: 5 },
      component: lazy(() => import('./charts/ConfidenceBandWidget').then(m => ({ default: m.ConfidenceBandWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          bandColor: { type: 'string', title: '区间颜色' },
          lineColor: { type: 'string', title: '主线颜色' },
          xLabels: { type: 'array', title: 'X轴标签' },
          mainSeries: { type: 'object', title: '主线' },
          upper: { type: 'array', title: '上界' },
          lower: { type: 'array', title: '下界' },
        },
      },
      defaultConfig: {
        bandColor: '#00D4FF',
        lineColor: '#00D4FF',
        showTick: true,
      },
    },

    {
      type: 'voronoi',
      name: 'Voronoi 图',
      description: '散点分布 + 最近邻区域划分',
      icon: 'ChartScatter',
      category: 'chart',
      defaultSize: { colSpan: 4, rowSpan: 3 },
      minSize: { colSpan: 2, rowSpan: 2 },
      maxSize: { colSpan: 8, rowSpan: 5 },
      component: lazy(() => import('./charts/VoronoiWidget').then(m => ({ default: m.VoronoiWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          pointColor: { type: 'string', title: '点颜色' },
          showCells: { type: 'boolean', title: '显示区域' },
          points: { type: 'array', title: '数据' },
        },
      },
      defaultConfig: {
        pointColor: '#00D4FF',
        showCells: true,
      },
    },

    {
      type: 'histogram',
      name: '直方图',
      description: '数据分布频率柱状图',
      icon: 'BarChart3',
      category: 'chart',
      defaultSize: { colSpan: 4, rowSpan: 3 },
      minSize: { colSpan: 2, rowSpan: 2 },
      maxSize: { colSpan: 8, rowSpan: 5 },
      component: lazy(() => import('./charts/HistogramWidget').then(m => ({ default: m.HistogramWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          binCount: { type: 'number', title: '分箱数量' },
          barColor: { type: 'string', title: '柱色' },
          data: { type: 'array', title: '数据' },
        },
      },
      defaultConfig: {
        binCount: 10,
        barColor: '#00D4FF',
        showTick: true,
      },
    },

    {
      type: 'group-chart',
      name: '分组柱状图',
      description: '多系列并列柱状图对比',
      icon: 'BarChart3',
      category: 'chart',
      defaultSize: { colSpan: 4, rowSpan: 3 },
      minSize: { colSpan: 2, rowSpan: 2 },
      maxSize: { colSpan: 8, rowSpan: 5 },
      component: lazy(() => import('./charts/GroupBarChartWidget').then(m => ({ default: m.GroupBarChartWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          showLabel: { type: 'boolean', title: '显示数值' },
          barWidth: { type: 'string', title: '柱宽' },
          xLabels: { type: 'array', title: 'X轴标签' },
          barSeries: { type: 'array', title: '数据系列' },
        },
      },
      defaultConfig: {
        direction: 'vertical',
        showLabel: false,
        showTick: true,
        colorBySign: false,
        barWidth: '40%',
        xLabels: ['周一', '周二', '周三', '周四', '周五'],
        barSeries: [
          { name: '系列1', data: [120, 200, 150, 80, 70] },
          { name: '系列2', data: [90, 150, 210, 130, 180] },
        ],
      },
    },

    {
      type: 'candlestick',
      name: '蜡烛图',
      description: 'K线图，展示开盘/收盘/最高/最低',
      icon: 'CandlestickChart',
      category: 'chart',
      defaultSize: { colSpan: 4, rowSpan: 3 },
      minSize: { colSpan: 3, rowSpan: 2 },
      maxSize: { colSpan: 8, rowSpan: 5 },
      component: lazy(() => import('./charts/CandlestickWidget').then(m => ({ default: m.CandlestickWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          upColor: { type: 'string', title: '阳线颜色' },
          downColor: { type: 'string', title: '阴线颜色' },
          candles: { type: 'array', title: '数据' },
        },
      },
      defaultConfig: {
        upColor: '#34d399',
        downColor: '#f87171',
        candles: [
          { name: '周一', open: 100, close: 105, high: 110, low: 98 },
          { name: '周二', open: 105, close: 102, high: 108, low: 100 },
          { name: '周三', open: 102, close: 115, high: 118, low: 101 },
          { name: '周四', open: 115, close: 112, high: 120, low: 110 },
          { name: '周五', open: 112, close: 118, high: 122, low: 108 },
        ],
      },
    },

    {
      type: 'water-pond',
      name: '水位球',
      description: '波浪水位动画',
      icon: 'Droplets',
      category: 'chart',
      defaultSize: { colSpan: 2, rowSpan: 2 },
      minSize: { colSpan: 1, rowSpan: 1 },
      maxSize: { colSpan: 4, rowSpan: 4 },
      component: lazy(() => import('./charts/WaterLevelPond').then(m => ({ default: m.WaterLevelPond }))),
      configSchema: {
        type: 'object',
        properties: {
          value: { type: 'number', title: '水位百分比' },
          title: { type: 'string', title: '标题' },
          suffix: { type: 'string', title: '后缀' },
          shape: { type: 'string', title: '形状', enum: ['rect', 'roundRect', 'round'] },
          waveHeight: { type: 'number', title: '波浪高度' },
          waveNum: { type: 'number', title: '波浪层数' },
        },
      },
      defaultConfig: {
        value: 60,
        title: '',
        titleColor: '#E8E8EC',
        titleFontSize: 14,
        suffix: '%',
        shape: 'round',
        waveHeight: 30,
        waveNum: 3,
      },
    },

    {
      type: 'gauge-chart',
      name: '仪表盘',
      description: '单值半圆进度表',
      icon: 'Gauge',
      category: 'chart',
      defaultSize: { colSpan: 2, rowSpan: 2 },
      minSize: { colSpan: 1, rowSpan: 1 },
      maxSize: { colSpan: 4, rowSpan: 4 },
      component: lazy(() => import('./charts/GaugeWidget').then(m => ({ default: m.GaugeWidget }))),
      configSchema: {
        type: 'object',
        properties: {
          value: { type: 'number', title: '当前值' },
          min: { type: 'number', title: '量程下限' },
          max: { type: 'number', title: '量程上限' },
          name: { type: 'string', title: '名称' },
          unit: { type: 'string', title: '单位' },
          progressColor: { type: 'string', title: '进度颜色' },
          trackColor: { type: 'string', title: '轨道颜色' },
          showProgress: { type: 'boolean', title: '进度弧' },
          valueAnimation: { type: 'boolean', title: '数值动画' },
          showTick: { type: 'boolean', title: '刻度指针' },
        },
      },
      defaultConfig: {
        value: 65,
        min: 0,
        max: 100,
        name: '负载率',
        unit: '%',
        progressColor: '#00D4FF',
        trackColor: 'rgba(255,255,255,0.08)',
        showProgress: true,
        valueAnimation: true,
        showTick: true,
      },
    },

  ]);

  console.log(
    `[Widgets] ${widgetRegistry.getAll().length} widgets ready:`,
    widgetRegistry.getAll().map(w => w.type).join(', '),
  );
}
